version: '3.9'

services:
  elastic-node01:
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - VIRTUAL_PORT=9200
      - VIRTUAL_HOST=elasitcsearch.$PROJECT_NAME.docker
      - CERT_NAME=$CERT_NAME
    volumes:
      - elastic-data01:/usr/share/elasticsearch/data

  kibana:
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic-node01:9200
      - ELASTICSEARCH_HOSTS=["http://elastic-node01:9200"]
      - VIRTUAL_PORT=5601
      - VIRTUAL_HOST=kibana.$PROJECT_NAME.docker
      - CERT_NAME=$CERT_NAME
    depends_on:
      - elastic-node01

volumes:
  elastic-data01:
