version: '3.9'

services:
  elastic-node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    depends_on:
      - elastic-node01
    environment:
      - TELEMETRY_ENABLED=false
